sudo: false
dist: trusty
language: ruby
rvm:
- 2.5.1
addons:
  postgresql: '9.6'
cache:
- bundler
before_install:
- gem update --system --quiet
- gem install bundler -v "~>2.0.1" --no-document
install:
- bundle install --jobs 16
branches:
  only:
    - master
before_script:
- psql -c 'create database inquiries_maker_test;' -U postgres
- cp config/database.travis.yml config/database.yml
- RAILS_ENV=test bundle exec rake db:create db:migrate
- bundle exec rspec
script:
- openssl aes-256-cbc -k $DEPLOY_KEY -in config/deploy_id_rsa_enc_travis -d -a -out config/deploy_id_rsa
- chmod 600 config/deploy_id_rsa
- eval "$(ssh-agent -s)"
- ssh-add config/deploy_id_rsa
- echo "Ready to deploy! ✅"
after_success:
- "[[ $TRAVIS_BRANCH = 'master' ]] && bundle exec cap production deploy"
- "[[ $TRAVIS_BRANCH = 'master' ]] && bundle exec cap production workers:stop"
- "[[ $TRAVIS_BRANCH = 'master' ]] && bundle exec cap production workers:start"
- "[[ $TRAVIS_BRANCH = 'master' ]] && bundle exec cap production workers:ids"
after_failure:
- echo "Can not deploy! ❌"
after_script:
- bundle exec cap production notify:telegram
- echo "All done! 💚"
env:
  global:
  - secure: V0Ad6+BwFi945Z3+obIp72cTh8oYozR/oEr8IUJU7VRaK90pbQ+WDK5sqnUQ/IpC5rVD3XNascXf1STmD3D+wPuv4RYTTwmL2QFak8avWkEg898RgPYKpQjUWdKwJ5tAouxq3NIRzNnhCsSiRhiI5I7vD7lbmeW3rohNxz9zJCGlmzviQQP8OhiF8SyBQlq3fLzws7QFCyurie36M6+PZh9okk2AXjl+jDWqXNNS81mDCM2JOVPwzb5OEOEf8FY7S2rl43+izvV3bmA2p1Ug0rwU9sjJkNwtBAKnVV49M8fVlu3yIJY2TweYwXtsk/lGVFtLZmIY5A0Sd4RDgyfSyNnihTVFIxt+Dy7EXnDSUZOQ80mYkcCfqj/WNFdycWWPB5tA8kv9IPVt1SRpAXPqhGDUYvKHBqXS8Y44bt/BybLtFNHT/jpxC3dkJ5G9Ho2WgiTZniaSx2jVM2/J4H4OMM7CkBLwa0GEkTmvZZBM/OnXdGw1hJwwel/6ylIBaTwXlKhnaE/zK1BgzVbDoEzRCxkrNV+96Rhfw8uPOFYEgxOH4Q0BObEeBmvpSiNZfGUhEyyUFRTRh+/n880nDGD2wXQg55FjevYo+j6jfkkXpvilyqOS5jsowEsKTRbX2CDVU25VPDSf8+nbfyKxH+wsGGKu4T0BUBMs4XXvmSHYXtQ=
  - secure: mVBgYNU9RS02RC/giRZvIqW5gmPRlo7QOUTLGGereJ44JNmgO4yCKXxxCirhb28vnK9PxIhgU/6vXcElkfeJaJKwQl8Q9H+JsYYfLus0jsPnmbkECtjav/oYNaaU6HGUGm/1kVD4JW5OVVo2k2i8VPCCdWMjFBtRCl7VcjgR//QuiFhlDv4VNChHc62TWVfddAc1/Wmk8a22x8JiWyTWIVLXli9kjBNk8R3ylxbuo/IXGV45E0r+noPrWqxStH5O3xz4WyWaJrrg2Nc8OoOmGnXgZeXzUymYw1RbmAMo5qDFhGQQ7tVDjDKVaTy9OPtgpexP3jf1ToQUj/Oa4QNfifOoAWWS/8nH3Pn/klPlVRCQPzbJpJavfMrEF+/azy4e9XVl4fOIrk97mRp+GxxPLStier37S9vpVYAY2GrLMhHrSDl2AtkwghwBiy0xH1LqCRkOxqGzOdxq/9e6xSsyxDhnZWK5xl3dcgCnzu/ChXk1UNzc8CDFukzFDXd3obtp/WucK9gMHd7TFacbhwIfiHP8rBu9HwTXKbCoQWWCLMXUG5HpZIprRXIBO4DTNzkBvtTrYXElo3FmC3EjQSHxCZGfH5Uf4PsWVcGI+H3eQHtgKG9rWXK2zn7gyxOpAYbrLdW2yHr496N6jr96O2vasTYcUjEpodxrC0aRT9pMWXo=
