# docker-compose.yml

version: '3'
services:
  web:
    depends_on:
      - db
      - broker
    image: kaygeee/inquiries-maker:latest
    ports:
      - "80:80"
    environment:
      - RAILS_MASTER_KEY=$RAILS_MASTER_KEY
  worker:
    depends_on:
      - broker
      - db
      - web
    image: kaygeee/inquiries-maker:latest
    command: rake sneakers:run
    environment:
      - RAILS_MASTER_KEY=$RAILS_MASTER_KEY
  broker:
    depends_on:
      - db
    image: rabbitmq
  db:
    image: postgres
    volumes:
      - /inquiries-maker/db/dumps
    # We're mounting this folder so we can backup/restore database dumps from our app folder.
