# edit your own encrypted credientials and replace these values with your own. and add the RAILS_MASTER_KEY in a .env file next to the docker-compose file
secret_key_base: your-very-long-secret-key-base-here

production:
  gmail_username: gmail_user_name
  gmail_password: password
  rabbitmq_amqp_uri: amqp://guest:guest@broker:5672 #has broker for docker!!
  movu_staging_url: movu_staging_url
  movu_api_path: movu_api_path
  movu_partner_token: partner_token
  database_url: database_url
  inquiries_maker_database_password: inquiries_maker_database_password
development:
  gmail_username: gmail_user_name
  gmail_password: password
  rabbitmq_amqp_uri: amqp://guest:guest@127.0.0.1:5672 # this is the default!
  movu_staging_url: movu_staging_url
  movu_api_path: movu_api_path
  movu_partner_token: partner_token
  database_url: database_url
  inquiries_maker_database_password: inquiries_maker_database_password
test:
  gmail_username: gmail_user_name
  gmail_password: password
  rabbitmq_amqp_uri: amqp://guest:guest@127.0.0.1:5672 # this is the default!
  movu_staging_url: movu_staging_url
  movu_api_path: movu_api_path
  movu_partner_token: partner_token
  database_url: database_url
  inquiries_maker_database_password: inquiries_maker_database_password
