default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 15 } %>

development:
  <<: *default
  database: inquiries_maker_development
  url: <%= ENV['DATABASE_URL'] %>

test:
  <<: *default
  database: inquiries_maker_test

production:
  <<: *default
  database: inquiries_maker_production
  username: inquiries_maker
  password: <%= Rails.application.credentials.dig( Rails.env.to_sym, :inquiries_maker_database_password) %>
  url: <%= Rails.application.credentials.dig( Rails.env.to_sym, :database_url) %>
