User.create!([
  {email: "test@user.com", password: "123456", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2018-05-13 16:13:50", last_sign_in_at: "2018-05-13 16:13:50", current_sign_in_ip: "::1", last_sign_in_ip: "::1"}
])
MovingInquiry.create!([
  {partner_token: "MyString", locale: "de", client_first_name: "Raymundo", client_last_name: "Pouros", client_salutation: "Frau", client_email: "1@fake.com", client_mobile: "+41337871978", client_street_and_number: "Jarred Mission 7523", client_postal_code: "9594", client_city: "Brenzikofen", client_property_size: "size_7", is_moving_request: true, is_cleaning_request: false, moving_street_and_number: "Merle Mills 5727", moving_postal_code: "2177", moving_city: "Romanel-sur-Lausanne", moving_date: "2018-07-15"},
  {partner_token: "MyString", locale: "de", client_first_name: "Karlie", client_last_name: "Frami", client_salutation: "Mr", client_email: "2@fake.com", client_mobile: "0041229341315", client_street_and_number: "Carlie Shore 1636", client_postal_code: "3793", client_city: "Cama", client_property_size: "size_7", is_moving_request: true, is_cleaning_request: false, moving_street_and_number: "Rau Road 7033", moving_postal_code: "1721", moving_city: "Bettwiesen", moving_date: "2018-07-08"},
  {partner_token: "MyString", locale: "fr", client_first_name: "Asa", client_last_name: "Kuhn", client_salutation: "Frau", client_email: "3@fake.com", client_mobile: "0041522847852", client_street_and_number: "Beer Ford 11541", client_postal_code: "2101", client_city: "Göschenen", client_property_size: "size_4", is_moving_request: true, is_cleaning_request: false, moving_street_and_number: "Pagac Camp 429", moving_postal_code: "8615", moving_city: "Affoltern im Emmental", moving_date: "2018-05-18"},
  {partner_token: "MyString", locale: "fr", client_first_name: "Tommie", client_last_name: "Gleichner", client_salutation: "Frau", client_email: "4@fake.com", client_mobile: "0277180083", client_street_and_number: "Wuckert Haven 702", client_postal_code: "7170", client_city: "Huttwil", client_property_size: "size_5", is_moving_request: true, is_cleaning_request: false, moving_street_and_number: "Volkman Valleys 48887", moving_postal_code: "4561", moving_city: "Bussy-sur-Moudon", moving_date: "2018-06-29"},
  {partner_token: "MyString", locale: "en", client_first_name: "Daphney", client_last_name: "Nitzsche", client_salutation: "M.", client_email: "5@fake.com", client_mobile: "0041411526999", client_street_and_number: "Douglas Plaza 871", client_postal_code: "3299", client_city: "Arbon", client_property_size: "size_1", is_moving_request: true, is_cleaning_request: false, moving_street_and_number: "Haleigh Islands 23284", moving_postal_code: "1518", moving_city: "Bassins", moving_date: "2018-06-28"},
  {partner_token: "MyString", locale: "de", client_first_name: "Toy", client_last_name: "Senger", client_salutation: "Mrs", client_email: "6@fake.com", client_mobile: "0248916490", client_street_and_number: "Margie Cove 24603", client_postal_code: "5446", client_city: "Attiswil", client_property_size: "size_3", is_moving_request: true, is_cleaning_request: false, moving_street_and_number: "Bella Heights 66089", moving_postal_code: "3413", moving_city: "Chapelle (Glâne)", moving_date: "2018-06-01"},
  {partner_token: "MyString", locale: "de", client_first_name: "Finn", client_last_name: "Gibson", client_salutation: "Mme", client_email: "7@fake.com", client_mobile: "0041333490668", client_street_and_number: "Olga Streets 5144", client_postal_code: "7234", client_city: "Valcolla", client_property_size: "size_3", is_moving_request: true, is_cleaning_request: false, moving_street_and_number: "Wunsch Way 171", moving_postal_code: "7210", moving_city: "La Ferrière", moving_date: "2018-06-03"},
  {partner_token: "MyString", locale: "de", client_first_name: "Braeden", client_last_name: "Parker", client_salutation: "Mrs", client_email: "8@fake.com", client_mobile: "0041764578270", client_street_and_number: "Orrin Loaf 10280", client_postal_code: "7600", client_city: "Chavannes-des-Bois", client_property_size: "size_2", is_moving_request: true, is_cleaning_request: false, moving_street_and_number: "Mossie Camp 18641", moving_postal_code: "1698", moving_city: "Gadmen", moving_date: "2018-07-21"},
  {partner_token: "MyString", locale: "de", client_first_name: "Tyrese", client_last_name: "Heaney", client_salutation: "M.", client_email: "9@fake.com", client_mobile: "0041554318264", client_street_and_number: "Jamison Turnpike 70408", client_postal_code: "9957", client_city: "Dörflingen", client_property_size: "size_1", is_moving_request: true, is_cleaning_request: false, moving_street_and_number: "Kilback Summit 67089", moving_postal_code: "3402", moving_city: "Bonstetten", moving_date: "2018-06-25"},
  {partner_token: "MyString", locale: "fr", client_first_name: "Vergie", client_last_name: "Wiza", client_salutation: "Mr", client_email: "10@fake.com", client_mobile: "0041413740883", client_street_and_number: "Boris Islands 4526", client_postal_code: "8298", client_city: "Thörigen", client_property_size: "size_1", is_moving_request: true, is_cleaning_request: false, moving_street_and_number: "Annie Island 94273", moving_postal_code: "3717", moving_city: "Bure", moving_date: "2018-06-04"},
  {partner_token: "MyString", locale: "de", client_first_name: "Nannie", client_last_name: "Kiehn", client_salutation: "Mme", client_email: "11@fake.com", client_mobile: "0041761718121", client_street_and_number: "Kunze Plains 9149", client_postal_code: "4842", client_city: "Emmetten", client_property_size: "size_6", is_moving_request: true, is_cleaning_request: false, moving_street_and_number: "Beau Village 97467", moving_postal_code: "2312", moving_city: "Pfeffikon", moving_date: "2018-06-27"},
  {partner_token: "MyString", locale: "de", client_first_name: "Josiah", client_last_name: "Ankunding", client_salutation: "M.", client_email: "12@fake.com", client_mobile: "+41321190832", client_street_and_number: "Mueller Inlet 8907", client_postal_code: "5384", client_city: "Büsserach", client_property_size: "size_4", is_moving_request: true, is_cleaning_request: false, moving_street_and_number: "Georgette Mount 847", moving_postal_code: "7686", moving_city: "Ulrichen", moving_date: "2018-08-07"},
  {partner_token: "MyString", locale: "de", client_first_name: "Travon", client_last_name: "Shields", client_salutation: "Mrs", client_email: "13@fake.com", client_mobile: "0041266853826", client_street_and_number: "Ryan Junction 5851", client_postal_code: "3258", client_city: "Rothrist", client_property_size: "size_2", is_moving_request: true, is_cleaning_request: false, moving_street_and_number: "Doyle Cape 129", moving_postal_code: "2429", moving_city: "Castaneda", moving_date: "2018-07-12"},
  {partner_token: "MyString", locale: "fr", client_first_name: "Xavier", client_last_name: "Kub", client_salutation: "Mrs", client_email: "14@fake.com", client_mobile: "0041262997779", client_street_and_number: "Kemmer Neck 55126", client_postal_code: "4723", client_city: "Dompierre (FR)", client_property_size: "size_1", is_moving_request: true, is_cleaning_request: false, moving_street_and_number: "Hudson Isle 361", moving_postal_code: "4847", moving_city: "Quinto", moving_date: "2018-06-20"},
  {partner_token: "MyString", locale: "fr", client_first_name: "Ambrose", client_last_name: "Windler", client_salutation: "Herr", client_email: "15@fake.com", client_mobile: "+41623493703", client_street_and_number: "Justice Lock 969", client_postal_code: "1305", client_city: "Dorénaz", client_property_size: "size_5", is_moving_request: true, is_cleaning_request: false, moving_street_and_number: "Valentina Lights 736", moving_postal_code: "1399", moving_city: "Campo (Vallemaggia)", moving_date: "2018-05-24"}
])

# require 'factory_bot_rails'
# require 'faker'
# 15.times do |i|
#   i = i+1
#   FactoryBot.create(:moving_inquiry, client_email: "#{i}@fake.com", client_property_size: ["size_1", "size_2", "size_3", "size_4", "size_5", "size_6", "size_7", "size_8"].shuffle.first)
# end
# # ActiveRecord::Base.transaction do
# # end
SeedMigration::Migrator.bootstrap()
